# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GliaConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('conversationID', models.IntegerField()),
                ('conversationTitle', models.CharField(max_length=200)),
                ('counselorID', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='GliaCounselor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('counselorName', models.CharField(max_length=100)),
                ('counselorBio', models.TextField()),
                ('counselorImageURL', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='GliaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gliaID', models.CharField(max_length=100)),
                ('conversationID', models.IntegerField()),
                ('progress', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
