# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gliacounselor',
            name='counselorID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
