# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_gliacounselor_counselorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gliaconversation',
            name='counselorID',
            field=models.CharField(max_length=100),
        ),
    ]
